name: build_lmi_popup_fix
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
       - uses: actions/checkout@master  
       - name: 获取配置
         run: |
            source "$GITHUB_WORKSPACE"/resource/config.env
            echo "ROM_URL=$ROM_URL" >> $GITHUB_ENV
            echo "camera1=$camera1" >> $GITHUB_ENV
            echo "camera2=$camera2" >> $GITHUB_ENV
       - name: 1.安装依赖
         run: |
            sudo apt install python3 python3-pip aria2 zip p7zip-full zipalign
            sudo apt --fix-broken install
            sudo apt update --fix-missing
            pip3 install --upgrade pip
            pip3 install aliyundrive-webdav
            pip3 install pycryptodome
            pip3 install docopt
            pip3 install requests
            pip3 install beautifulsoup4
            pip3 install --ignore-installed pyyaml
            curl https://rclone.org/install.sh | sudo bash
            mkdir -p ~/.config/rclone/
            unzip -P ${{ secrets.PASSWORD }} "$GITHUB_WORKSPACE"/tools/rclone.zip -d ~/.config/rclone/
            curl -fsSL "https://nn.ci/alist.sh" | sudo bash -s install
            sudo systemctl stop alist
            sudo mv -f /home/runner/.config/rclone/data.db /opt/alist/data
            sudo systemctl start alist
       - name: 2.下载系统包
         run: |
            aria2c -x16 -j$(nproc) -U "Mozilla/5.0" -d "$GITHUB_WORKSPACE" ${{ env.ROM_URL }}
       - name: 3.解包
         run: |
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/payload-dumper-go
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/brotli
            mkdir -p "$GITHUB_WORKSPACE"/PSYCHE
            mkdir -p "$GITHUB_WORKSPACE"/images
            mkdir -p "$GITHUB_WORKSPACE"/simages
            mkdir -p "$GITHUB_WORKSPACE"/zip
            URL=${{ env.ROM_URL }}
            ZIP_NAME_PSYCHE=${URL##*/}
            7z x "$GITHUB_WORKSPACE"/$ZIP_NAME_PSYCHE -r -o"$GITHUB_WORKSPACE"/PSYCHE
            rm -rf "$GITHUB_WORKSPACE"/$ZIP_NAME_PSYCHE
            for i in system
            do
                "$GITHUB_WORKSPACE"/tools/payload-dumper-go -p $i "$GITHUB_WORKSPACE"/PSYCHE/payload.bin
                mv "$GITHUB_WORKSPACE"/payload/$i.img "$GITHUB_WORKSPACE"/images/$i.img
            done
            rm -rf "$GITHUB_WORKSPACE"/payload
            rm -rf "$GITHUB_WORKSPACE"/PSYCHE
            sudo python3 "$GITHUB_WORKSPACE"/tools/imgextractorLinux.py "$GITHUB_WORKSPACE"/images/system.img "$GITHUB_WORKSPACE"/images
            rm -rf "$GITHUB_WORKSPACE"/images/system.img
       - name: 4.替换相关文件
         run: |
            mkdir -p "$GITHUB_WORKSPACE"/framework
            sudo cp -rf "$GITHUB_WORKSPACE"/images/system/system/framework/miui-services.jar "$GITHUB_WORKSPACE"/framework
            sudo cp -rf "$GITHUB_WORKSPACE"/images/system/system/framework/framework-ext-res/framework-ext-res.apk "$GITHUB_WORKSPACE"/framework
       - name: 5.打包
         run: |
            sudo 7z a "$GITHUB_WORKSPACE"/zip/miui_LMIPRE_popup.zip "$GITHUB_WORKSPACE"/framework/*
            sudo rm -rf "$GITHUB_WORKSPACE"/framework
            mv "$GITHUB_WORKSPACE"/zip/miui_LMIPRE_popup.zip "$GITHUB_WORKSPACE"/zip/miui_LMIPRE_popup_fix.zip
            echo "artifact_name=miui_LMIPRE_popup_fix" >> $GITHUB_ENV
            cd "$GITHUB_WORKSPACE"
            touch file.log
            echo "miui_LMIPRE_"${{ env.date }}"_popup_fix.zip" > file.log
       - name: 6.上传到Github Release
         uses: ncipollo/release-action@main
         with:
           artifacts: ${{ github.workspace }}/zip/*
           name: "${{ env.date }}_popup_fix"
           tag: "${{ env.date }}_popup_fix"
           bodyFile: "${{ github.workspace }}/file.log"
           allowUpdates: true
           artifactErrorsFailBuild: true
           token: ${{ secrets.GITHUB_TOKEN }}
       - name: 7.删除工作流运行
         uses: Mattraks/delete-workflow-runs@v2
         with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
