name: build_lmi_popup_fix
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
       - uses: actions/checkout@master  
       - name: 获取配置
         run: |
            source "$GITHUB_WORKSPACE"/resource/config.env
            echo "ROM_URL=$ROM_URL" >> $GITHUB_ENV
            echo "date=$(echo $ROM_URL | cut -d"/" -f4)" >> $GITHUB_ENV
       - name: 1.安装依赖
         run: |
            sudo apt install python3 python3-pip aria2 zip p7zip-full zipalign
            sudo apt --fix-broken install
            sudo apt update --fix-missing
            pip3 install --upgrade pip
            pip3 install pycryptodome
            pip3 install setuptools
            pip3 install docopt
            pip3 install requests
            pip3 install beautifulsoup4
            pip3 install --ignore-installed pyyaml
       - name: 2.下载系统包
         run: |
            aria2c -x16 -j$(nproc) -U "Mozilla/5.0" -d "$GITHUB_WORKSPACE" ${{ env.ROM_URL }}
       - name: 3.解包
         run: |
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/payload-dumper-go
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/brotli
            mkdir -p "$GITHUB_WORKSPACE"/PSYCHE
            mkdir -p "$GITHUB_WORKSPACE"/images
            mkdir -p "$GITHUB_WORKSPACE"/simages
            mkdir -p "$GITHUB_WORKSPACE"/zip
            URL=${{ env.ROM_URL }}
            ZIP_NAME_PSYCHE=${URL##*/}
            7z x "$GITHUB_WORKSPACE"/$ZIP_NAME_PSYCHE -r -o"$GITHUB_WORKSPACE"/PSYCHE
            rm -rf "$GITHUB_WORKSPACE"/$ZIP_NAME_PSYCHE
            for i in system
            do
                "$GITHUB_WORKSPACE"/tools/payload-dumper-go -p $i "$GITHUB_WORKSPACE"/PSYCHE/payload.bin
                mv "$GITHUB_WORKSPACE"/payload/$i.img "$GITHUB_WORKSPACE"/images/$i.img
            done
            rm -rf "$GITHUB_WORKSPACE"/payload
            rm -rf "$GITHUB_WORKSPACE"/PSYCHE
            sudo python3 "$GITHUB_WORKSPACE"/tools/imgextractorLinux.py "$GITHUB_WORKSPACE"/images/system.img "$GITHUB_WORKSPACE"/images
            rm -rf "$GITHUB_WORKSPACE"/images/system.img
       - name: 4.替换相关文件
         run: |
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/apktool.jar
            Apktool="java -jar "$GITHUB_WORKSPACE"/tools/apktool.jar"
            echo 导入框架
            $Apktool if "$GITHUB_WORKSPACE"/images/system/system/app/miui/miui.apk
            $Apktool if "$GITHUB_WORKSPACE"/images/system/system/app/miuisystem/miuisystem.apk
            $Apktool if "$GITHUB_WORKSPACE"/images/system/system/framework/framework-res.apk
            $Apktool if "$GITHUB_WORKSPACE"/images/system/system/framework/framework-ext-res/framework-ext-res.apk
            sudo mkdir -p /root/.local/share/apktool/framework/
            sudo mv /home/runner/.local/share/apktool/framework/* /root/.local/share/apktool/framework/
            mkdir -p "$GITHUB_WORKSPACE"/popupfix
            cp -rf "$GITHUB_WORKSPACE"/images/system/system/framework/miui-services.jar "$GITHUB_WORKSPACE"/popupfix
            cp -rf "$GITHUB_WORKSPACE"/images/system/system/framework/framework-ext-res/framework-ext-res.apk "$GITHUB_WORKSPACE"/popupfix
            mkdir -p "$GITHUB_WORKSPACE"/popupfix/id
            cd "$GITHUB_WORKSPACE"/popupfix/id
            $Apktool d -q -b -f -m "$GITHUB_WORKSPACE"/popupfix/framework-ext-res.apk
            echo "- 解读id完成"
            idmod="$GITHUB_WORKSPACE"/popupfix/id/framework-ext-res/res/values/public.xml
            sudo sed -i 's/ //g' $idmod
            sudo sed -i 's/\"//g' $idmod
            sudo sed -i 's/\/>//g' $idmod
            sudo sed -i 's/<publictype=[^*]*name=//g' $idmod
            sudo sed -i 's/<?xmlversion=1\.0encoding=utf-8?>//g' $idmod
            sudo sed -i 's/<resources>//g' $idmod
            sudo sed -i 's/<\/resources>//g' $idmod
            sudo sed -i '/^$/d' $idmod
            sudo sed -i 's/\$//g' $idmod
            sudo sed -i 's/\.//g' $idmod
            echo "- 开始释放升降.jar"
            mkdir -p "$GITHUB_WORKSPACE"/popup
            cp -rf "$GITHUB_WORKSPACE"/images/system/system/framework/miui-services.jar "$GITHUB_WORKSPACE"/popup/miui-services.apk
            cd "$GITHUB_WORKSPACE"/popup
            $Apktool d -q -b -r -f -m "$GITHUB_WORKSPACE"/popup/miui-services.apk
            unzip -q -o -P ${{ secrets.POPUPFIX }} "$GITHUB_WORKSPACE"/resource/classes.zip -d "$GITHUB_WORKSPACE"/popup/miui-services/smali/
            source $idmod
            echo "- 填写修复升降所需要的资源id"
            mod="$GITHUB_WORKSPACE"/popup/miui-services/smali/com/miui/server/popupcamera/view/UpAndDownAnimationView.smali
            sudo sed -i "s/uucchw/$camera_close_high_waveid/g" $mod
            sudo sed -i "s/uu2cchw/$camera_close_high_wave2id/g" $mod
            sudo sed -i "s/uucclw/$camera_close_low_waveid/g" $mod
            sudo sed -i "s/uu2cclw/$camera_close_low_wave2id/g" $mod
            sudo sed -i "s/uucohw/$camera_open_high_waveid/g" $mod
            sudo sed -i "s/uu2cohw/$camera_open_high_wave2id/g" $mod
            sudo sed -i "s/uucolw/$camera_open_low_waveid/g" $mod
            sudo sed -i "s/uu2colw/$camera_open_low_wave2id/g" $mod
            sudo sed -i "s/h1ighwave/$highWaveid/g" $mod
            sudo sed -i "s/l1owwave/$lowWaveid/g" $mod
            sudo sed -i "s/uupchw/$pop_camera_high_waveid/g" $mod
            sudo sed -i "s/uu1pchw/$pop_camera_high_wave1id/g" $mod
            sudo sed -i "s/uu2pchw/$pop_camera_high_wave2id/g" $mod
            sudo sed -i "s/uu3pchw/$pop_camera_high_wave3id/g" $mod
            sudo sed -i "s/uu4pchw/$pop_camera_high_wave4id/g" $mod
            sudo sed -i "s/uu5pchw/$pop_camera_high_wave5id/g" $mod
            sudo sed -i "s/uupclw/$pop_camera_low_waveid/g" $mod
            sudo sed -i "s/uu1pclw/$pop_camera_low_wave1id/g" $mod
            sudo sed -i "s/uu2pclw/$pop_camera_low_wave2id/g" $mod
            sudo sed -i "s/uu3pclw/$pop_camera_low_wave3id/g" $mod
            sudo sed -i "s/uu4pclw/$pop_camera_low_wave4id/g" $mod
            sudo sed -i "s/uu5pclw/$pop_camera_low_wave5id/g" $mod
            sudo sed -i "s/uuuadav/$up_and_down_animation_viewid/g" $mod
            echo "- 填写完成，开始打包"
            cd "$GITHUB_WORKSPACE"/popup/miui-services/
            $Apktool b -q -f -c "$GITHUB_WORKSPACE"/popup/miui-services/ -o miui-services.jar
            sudo cp -rf "$GITHUB_WORKSPACE"/popup/miui-services/miui-services.jar "$GITHUB_WORKSPACE"/images/system/system/framework/miui-services.jar
            mkdir -p "$GITHUB_WORKSPACE"/framework
            cp -rf "$GITHUB_WORKSPACE"/popup/miui-services/miui-services.jar "$GITHUB_WORKSPACE"/framework/miui-services.jar
       - name: 5.打包
         run: |
            sudo 7z a "$GITHUB_WORKSPACE"/zip/miui_LMIPRE_popup.zip "$GITHUB_WORKSPACE"/framework/*
            sudo rm -rf "$GITHUB_WORKSPACE"/framework
            mv "$GITHUB_WORKSPACE"/zip/miui_LMIPRE_popup.zip "$GITHUB_WORKSPACE"/zip/miui_LMIPRE_"${{ env.date }}"_popup_fix.zip
            echo "artifact_name=miui_LMIPRE_popup_fix" >> $GITHUB_ENV
            cd "$GITHUB_WORKSPACE"
            touch file.log
            echo "miui_LMIPRE_"${{ env.date }}"_popup_fix.zip" > file.log
       - name: 6.上传到Github Release
         uses: ncipollo/release-action@main
         with:
           artifacts: ${{ github.workspace }}/zip/*
           name: "${{ env.date }}_popup_fix"
           tag: "${{ env.date }}_popup_fix"
           bodyFile: "${{ github.workspace }}/file.log"
           allowUpdates: true
           artifactErrorsFailBuild: true
           token: ${{ secrets.GITHUB_TOKEN }}
       - name: 7.删除工作流运行
         uses: Mattraks/delete-workflow-runs@v2
         with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
