name: build_lmi_system_beta_rw
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
       - uses: actions/checkout@master
       - name: 获取配置
         run: |
            source "$GITHUB_WORKSPACE"/config.env
            echo "ROM_URL=$ROM_URL" >> $GITHUB_ENV
            echo "camera1=$camera1" >> $GITHUB_ENV
            echo "camera2=$camera2" >> $GITHUB_ENV
       - name: 1.安装依赖
         run: |
            sudo apt install python3 python3-pip aria2 zip p7zip-full zipalign
            sudo apt --fix-broken install
            sudo apt update --fix-missing
            pip3 install --upgrade pip
            pip3 install aliyundrive-webdav
            pip3 install pycryptodome
            pip3 install docopt
            pip3 install requests
            pip3 install beautifulsoup4
            pip3 install --ignore-installed pyyaml
       - name: 2.下载系统包
         run: |
            aria2c -x16 -j$(nproc) -U "Mozilla/5.0" -d "$GITHUB_WORKSPACE" ${{ env.ROM_URL }}
       - name: 3.解包
         run: |
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/payload-dumper-go
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/brotli
            mkdir -p "$GITHUB_WORKSPACE"/PSYCHE
            mkdir -p "$GITHUB_WORKSPACE"/LMI
            mkdir -p "$GITHUB_WORKSPACE"/images
            mkdir -p "$GITHUB_WORKSPACE"/simages
            mkdir -p "$GITHUB_WORKSPACE"/zip
            mkdir -p "$GITHUB_WORKSPACE"/firmware
            URL=${{ env.ROM_URL }}
            ZIP_NAME_PSYCHE=${URL##*/}
            7z x "$GITHUB_WORKSPACE"/$ZIP_NAME_PSYCHE -r -o"$GITHUB_WORKSPACE"/PSYCHE
            rm -rf "$GITHUB_WORKSPACE"/$ZIP_NAME_PSYCHE
            "$GITHUB_WORKSPACE"/tools/brotli -d "$GITHUB_WORKSPACE"/LMI/vendor.new.dat.br
            rm -rf "$GITHUB_WORKSPACE"/LMI/vendor.new.dat.br
            python3 "$GITHUB_WORKSPACE"/tools/sdat2img.py "$GITHUB_WORKSPACE"/LMI/vendor.transfer.list "$GITHUB_WORKSPACE"/LMI/vendor.new.dat "$GITHUB_WORKSPACE"/LMI/vendor.img
            rm -rf "$GITHUB_WORKSPACE"/LMI/vendor.patch.dat
            rm -rf "$GITHUB_WORKSPACE"/LMI/vendor.transfer.list
            rm -rf "$GITHUB_WORKSPACE"/LMI/vendor.new.dat
            echo "vendor_size=$(sudo du -sb "$GITHUB_WORKSPACE"/LMI/vendor.img | awk {'print $1'})" >> $GITHUB_ENV
            sudo python3 "$GITHUB_WORKSPACE"/tools/imgextractorLinux.py "$GITHUB_WORKSPACE"/LMI/vendor.img "$GITHUB_WORKSPACE"/LMI
            rm -rf "$GITHUB_WORKSPACE"/LMI/vendor.img
            for i in system
            do
                "$GITHUB_WORKSPACE"/tools/payload-dumper-go -p $i "$GITHUB_WORKSPACE"/PSYCHE/payload.bin
                mv "$GITHUB_WORKSPACE"/payload/$i.img "$GITHUB_WORKSPACE"/images/$i.img
            done
            rm -rf "$GITHUB_WORKSPACE"/payload
            rm -rf "$GITHUB_WORKSPACE"/PSYCHE
            echo "system_size=$(sudo du -sb "$GITHUB_WORKSPACE"/images/system.img | awk {'print $1'})" >> $GITHUB_ENV
            sudo python3 "$GITHUB_WORKSPACE"/tools/imgextractorLinux.py "$GITHUB_WORKSPACE"/images/system.img "$GITHUB_WORKSPACE"/images
            rm -rf "$GITHUB_WORKSPACE"/images/system.img
       - name: 4.替换相关文件
         run: |
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/apktool.jar
            Apktool="java -jar "$GITHUB_WORKSPACE"/tools/apktool.jar"
            sudo mkdir -p "$GITHUB_WORKSPACE"/images/system/system/etc/audio
            sudo rm -rf "$GITHUB_WORKSPACE"/images/product/etc/device_features/*
            sudo rm -rf "$GITHUB_WORKSPACE"/images/product/overlay/DeviceAndroidConfig.apk
            sudo rm -rf "$GITHUB_WORKSPACE"/images/product/overlay/DeviceConfig.apk
            sudo cp -f "$GITHUB_WORKSPACE"/AospFrameworkResOverlay.apk "$GITHUB_WORKSPACE"/images/product/overlay/
            sudo cp -f "$GITHUB_WORKSPACE"/DevicesAndroidOverlay.apk "$GITHUB_WORKSPACE"/images/product/overlay/
            sudo cp -f "$GITHUB_WORKSPACE"/DevicesOverlay.apk "$GITHUB_WORKSPACE"/images/product/overlay/
            sudo cp -f "$GITHUB_WORKSPACE"/lmi.xml "$GITHUB_WORKSPACE"/images/product/etc/device_features/
            sudo cp -f "$GITHUB_WORKSPACE"/lmipro.xml "$GITHUB_WORKSPACE"/images/product/etc/device_features/
            sudo sed -i "/ro.miui.notch/d" "$GITHUB_WORKSPACE"/images/product/etc/build.prop
            sudo rm -rf "$GITHUB_WORKSPACE"/images/system/cache
            sudo mkdir -p "$GITHUB_WORKSPACE"/images/system/cache
            sudo sed -i 's/ro.product.mod_device=[^*]*/ro.product.mod_device=lmi_pre/' "$GITHUB_WORKSPACE"/images/system/system/build.prop
            sudo sed -i 's/ro.miui.cust_device=[^*]*/ro.miui.cust_device=lmi/' "$GITHUB_WORKSPACE"/images/system/system/build.prop
            sudo rm -rf "$GITHUB_WORKSPACE"/LMI/vendor/recovery-from-boot.p
            sudo rm -rf "$GITHUB_WORKSPACE"/LMI/vendor/bin/install-recovery.sh
            sudo sed -i "/ro.vendor.audio.game.effect/d" "$GITHUB_WORKSPACE"/LMI/vendor/build.prop
            sudo sed -i "/import/i ro.vendor.audio.support.sound.id=true\nro.vendor.audio.voip.assistant=true\nro.vendor.audio.aiasst.support=true\nro.vendor.media.video.frc.support=true\nro.vendor.audio.spk.stereo=true\nro.vendor.audio.vocal.support=true\nro.vendor.audio.surround.support=true\nro.vendor.audio.spk.clean=true\nro.vendor.video_box.version=2" "$GITHUB_WORKSPACE"/LMI/vendor/build.prop
            sudo unzip -o "$GITHUB_WORKSPACE"/nfc.zip -d "$GITHUB_WORKSPACE"/images/system_ext
            sudo unzip -o "$GITHUB_WORKSPACE"/audio.zip -d "$GITHUB_WORKSPACE"/images/system/system/media/audio/ui/
            sudo unzip -o "$GITHUB_WORKSPACE"/etc.zip -d "$GITHUB_WORKSPACE"/images/system/system/etc/audio/
            sudo mkdir -p "$GITHUB_WORKSPACE"/MiLink/
            $Apktool d -q -r -f -o "$GITHUB_WORKSPACE"/MiLink/ "$GITHUB_WORKSPACE"/images/system/system/app/MiLinkCirculate/MiLinkCirculate.apk
            mod="$GITHUB_WORKSPACE"/MiLink/smali*/com/miui/circulate/world/permission/method/PermissionCheck\$BaseCheck.smali
            sudo sed -i '/^.method public check()Z/,/^.end method/{//!d}' $mod
            sudo sed -i -e '/^.method public check()Z/a\    .locals 1\n\n    const/4 v0, 0x1\n\n   return v0' $mod
            $Apktool b -q -f -o "$GITHUB_WORKSPACE"/MiLink/MiLinkCirculate.apk "$GITHUB_WORKSPACE"/MiLink/
            cd "$GITHUB_WORKSPACE"/MiLink/build/apk
            sudo 7z a "$GITHUB_WORKSPACE"/images/system/system/app/MiLinkCirculate/MiLinkCirculate.apk ./*.dex -mx0
            sudo rm -rf "$GITHUB_WORKSPACE"/images/system/system/app/MiLinkCirculate/oat
            sudo mv "$GITHUB_WORKSPACE"/images/system/system/app/MiLinkCirculate/MiLinkCirculate.apk "$GITHUB_WORKSPACE"/MiLink/MiLinkCirculate.apk
            sudo zipalign -v 4 "$GITHUB_WORKSPACE"/MiLink/MiLinkCirculate.apk "$GITHUB_WORKSPACE"/images/system/system/app/MiLinkCirculate/MiLinkCirculate.apk
            sizes=0
            for files in MIGalleryLockscreen MIUIDriveMode MIUIDuokanReader MIUIGameCenter MIUINewHome MIUIYoupin; do
            device=$(find "$GITHUB_WORKSPACE"/images/system/system/data-app/ -name $files)
            for file in $device; do
            size=$(sudo du -sb $file | awk {'print $1'})
            sizes=$(echo "$sizes + $size" | bc)
            sudo rm -rf $file
            done
            done
            echo "sizes=$sizes" >> $GITHUB_ENV
            sudo mv -f "$GITHUB_WORKSPACE"/vbmeta.img "$GITHUB_WORKSPACE"/LMI/firmware-update
            sudo mv -f "$GITHUB_WORKSPACE"/vbmeta_system.img "$GITHUB_WORKSPACE"/LMI/firmware-update
            sudo cp -r "$GITHUB_WORKSPACE"/LMI/firmware-update "$GITHUB_WORKSPACE"/images
            sudo cp -f "$GITHUB_WORKSPACE"/LMI/boot.img "$GITHUB_WORKSPACE"/images
            sudo cp -r "$GITHUB_WORKSPACE"/META-INF "$GITHUB_WORKSPACE"/images
            sudo cp -f "$GITHUB_WORKSPACE"/dynamic_partitions_op_list "$GITHUB_WORKSPACE"/images
            sudo cp -r "$GITHUB_WORKSPACE"/LMI/* "$GITHUB_WORKSPACE"/images
            sudo rm -rf "$GITHUB_WORKSPACE"/LMI
            sudo rm -rf "$GITHUB_WORKSPACE"/MiLink
       - name: 5.打包
         run: |
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/mke2fs
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/e2fsdroid
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/img2simg
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/brotli
            URL=${{ env.ROM_URL }}
            DATE=${URL%/*}
            date=${DATE##*/}
            product_ota_size=$(echo "1048576 * 0 " | bc)
            product_size=$(echo "${{ env.product_size }} + $product_ota_size" | bc)
            product_size=$(echo "$product_size / 4096" | bc)
            vendor_ota_size=$(echo "1048576 * 0 " | bc)
            vendor_size=$(echo "${{ env.vendor_size }} + $vendor_ota_size" | bc)
            vendor_size=$(echo "$vendor_size / 4096" | bc)
            system_ext_ota_size=$(echo "1048576 * 1 " | bc)
            system_ext_size=$(echo "${{ env.system_ext_size }} + $system_ext_ota_size" | bc)
            system_ext_size=$(echo "$system_ext_size / 4096" | bc)
            system_ota_size=$(echo "1048576 * 36 " | bc)
            system_size=$(echo "${{ env.system_size }} + $system_ota_size" | bc)
            system_size=$(echo "$system_size - ${{ env.sizes }}" | bc)
            echo ${{ env.sizes }}
            echo $system_size
            system_size=$(echo "$system_size / 4096" | bc)
            UTC=$(date -u +%s)
            for i in system
            do
                sudo python3 "$GITHUB_WORKSPACE"/tools/fspatch.py "$GITHUB_WORKSPACE"/images/$i "$GITHUB_WORKSPACE"/images/TI_config/"$i"_fs_config
                "$GITHUB_WORKSPACE"/tools/mke2fs -O ^has_journal -L $i -I 256 -M /$i -m 0 -t ext4 -b 4096 "$GITHUB_WORKSPACE"/images/$i.img $(eval echo "$"$i"_size")
                sudo "$GITHUB_WORKSPACE"/tools/e2fsdroid -T 1230768000 -C "$GITHUB_WORKSPACE"/images/TI_config/"$i"_fs_config -S "$GITHUB_WORKSPACE"/images/TI_config/"$i"_file_contexts -f "$GITHUB_WORKSPACE"/images/$i -a /$i -e -s "$GITHUB_WORKSPACE"/images/$i.img
                resize2fs -f -M "$GITHUB_WORKSPACE"/images/$i.img
                eval "$i"_size=$(du -sb "$GITHUB_WORKSPACE"/images/$i.img | awk {'print $1'})
                sudo rm -rf "$GITHUB_WORKSPACE"/images/$i
            done
       - name: 5.打包
         uses: Mattraks/delete-workflow-runs@v2
         with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
