name: build_lmi_popup_fix
on: 
  workflow_dispatch:
    inputs:
      URL:
        description: '待操作的系统包下载地址'     
        required: true
        default: 'https://hugeota.d.miui.com/22.7.22/miui_PSYCHEPRE_22.7.22_07f86d2521_12.0.zip'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
       - uses: actions/checkout@master  
       - name: 1.安装依赖
         run: |
            sudo apt install python3 python3-pip aria2 zip p7zip-full
            sudo apt --fix-broken install
            sudo apt update --fix-missing
            pip3 install --upgrade pip
            pip3 install pycryptodome
            pip3 install docopt
            pip3 install requests
            pip3 install beautifulsoup4
            pip3 install --ignore-installed pyyaml
       - name: 2.下载系统包
         run: |
            aria2c -x16 -j$(nproc) -U "Mozilla/5.0" -d "$GITHUB_WORKSPACE" ${{ github.event.inputs.URL }}
       - name: 3.解包
         run: |
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/payload-dumper-go
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/brotli
            mkdir -p "$GITHUB_WORKSPACE"/PSYCHE
            mkdir -p "$GITHUB_WORKSPACE"/images
            mkdir -p "$GITHUB_WORKSPACE"/simages
            mkdir -p "$GITHUB_WORKSPACE"/zip
            URL=${{ github.event.inputs.URL }}
            ZIP_NAME_PSYCHE=${URL##*/}
            7z x "$GITHUB_WORKSPACE"/$ZIP_NAME_PSYCHE -r -o"$GITHUB_WORKSPACE"/PSYCHE
            rm -rf "$GITHUB_WORKSPACE"/$ZIP_NAME_PSYCHE
            for i in system
            do
                "$GITHUB_WORKSPACE"/tools/payload-dumper-go -p $i "$GITHUB_WORKSPACE"/PSYCHE/payload.bin
                mv "$GITHUB_WORKSPACE"/payload/$i.img "$GITHUB_WORKSPACE"/images/$i.img
            done
            rm -rf "$GITHUB_WORKSPACE"/payload
            rm -rf "$GITHUB_WORKSPACE"/PSYCHE
            sudo python3 "$GITHUB_WORKSPACE"/tools/imgextractorLinux.py "$GITHUB_WORKSPACE"/images/system.img "$GITHUB_WORKSPACE"/images
            rm -rf "$GITHUB_WORKSPACE"/images/system.img
       - name: 4.替换相关文件
         run: |
            mkdir -p "$GITHUB_WORKSPACE"/framework
            sudo cp -rf "$GITHUB_WORKSPACE"/images/system/system/framework/miui-services.jar "$GITHUB_WORKSPACE"/framework
            sudo cp -rf "$GITHUB_WORKSPACE"/images/system/system/framework/framework-ext-res/framework-ext-res.apk "$GITHUB_WORKSPACE"/framework
       - name: 5.打包
         run: |
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/mke2fs
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/e2fsdroid
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/img2simg
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/brotli
            
            sudo 7z a "$GITHUB_WORKSPACE"/zip/miui_LMIPRE_popup.zip "$GITHUB_WORKSPACE"/framework/*
            sudo rm -rf "$GITHUB_WORKSPACE"/framework

            mv "$GITHUB_WORKSPACE"/zip/miui_LMIPRE_popup.zip "$GITHUB_WORKSPACE"/zip/miui_LMIPRE_popup_fix.zip
            echo "artifact_name=miui_LMIPRE_popup_fix" >> $GITHUB_ENV
       - name: 6.上传到Artifact
         uses: actions/upload-artifact@v3
         with:
          name: ${{ env.artifact_name }}
          path: "./zip/*"
       - name: 7.删除工作流运行
         uses: Mattraks/delete-workflow-runs@v2
         with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
