name: modem_Transplant
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
       - uses: actions/checkout@master  
       - name: 获取配置
         run: |
            source "$GITHUB_WORKSPACE"/resource/config.env
            $ROM_URL=https://hugeota.d.miui.com/22.10.12/miui_PSYCHEPRE_22.10.12_b4a181fdac_12.0.zip
            echo "ROM_URL=$ROM_URL" >> $GITHUB_ENV
            echo "date=$(echo $ROM_URL | cut -d"/" -f4)" >> $GITHUB_ENV
       - name: 1.安装依赖
         run: |
            sudo apt install python3 python3-pip aria2 zip p7zip-full zipalign
            sudo apt --fix-broken install
            sudo apt update --fix-missing
            pip3 install --upgrade pip
            pip3 install aliyundrive-webdav
            pip3 install pycryptodome
            pip3 install docopt
            pip3 install requests
            pip3 install beautifulsoup4
            pip3 install --ignore-installed pyyaml
       - name: 2.下载系统包
         run: |
            aria2c -x16 -j$(nproc) -U "Mozilla/5.0" -d "$GITHUB_WORKSPACE" ${{ env.ROM_URL }}
            aria2c -x16 -j$(nproc) -U "Mozilla/5.0" -d "$GITHUB_WORKSPACE" https://hugeota.d.miui.com/22.7.19/miui_UMIPRE_22.7.19_c2ae8f91d4_12.0.zip
       - name: 3.解包
         run: |
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/payload-dumper-go
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/brotli
            mkdir -p "$GITHUB_WORKSPACE"/PSYCHE
            mkdir -p "$GITHUB_WORKSPACE"/images
            mkdir -p "$GITHUB_WORKSPACE"/simages
            mkdir -p "$GITHUB_WORKSPACE"/zip
            mkdir -p "$GITHUB_WORKSPACE"/firmware
            ZIP_NAME_PSYCHE=$(echo ${{ env.ROM_URL }} | cut -d"/" -f5)
            7z x "$GITHUB_WORKSPACE"/$ZIP_NAME_PSYCHE -r -o"$GITHUB_WORKSPACE"/PSYCHE
            rm -rf "$GITHUB_WORKSPACE"/$ZIP_NAME_PSYCHE
            ZIP_NAME_LMI=miui_UMIPRE_22.7.19_c2ae8f91d4_12.0.zip
            7z x "$GITHUB_WORKSPACE"/$ZIP_NAME_LMI -r -o"$GITHUB_WORKSPACE"/images firmware-update
            for i in modem
            do
                "$GITHUB_WORKSPACE"/tools/payload-dumper-go -p $i "$GITHUB_WORKSPACE"/PSYCHE/payload.bin
                mv "$GITHUB_WORKSPACE"/payload/$i.img "$GITHUB_WORKSPACE"/images/$i.img
            done
            rm -rf "$GITHUB_WORKSPACE"/payload
            rm -rf "$GITHUB_WORKSPACE"/PSYCHE
       - name: 4.替换相关文件
         run: |
            mkdir -p "$GITHUB_WORKSPACE"/modem "$GITHUB_WORKSPACE"/modem1
            sudo mount -v -t vfat ""$GITHUB_WORKSPACE"/images/modem.img" ""$GITHUB_WORKSPACE"/modem/"
            sudo mount -v -t vfat ""$GITHUB_WORKSPACE"/images/firmware-update/NON-HLOS.bin" ""$GITHUB_WORKSPACE"/modem1/"
            for i in $(ls "$GITHUB_WORKSPACE"/modem/image/)
            do
            if [[ $i != modem_pr ]] && [[ $i != sdx55 ]] && [[ $i != sdx55m ]];then
              sudo rm -rf "$GITHUB_WORKSPACE"/modem/image/$i
            fi
            done
            for i in $(sudo ls "$GITHUB_WORKSPACE"/modem1/image/)
            do
            if [[ $i = modem_pr ]] || [[ $i = sdx55 ]] || [[ $i = sdx55m ]];then
              sudo rm -rf "$GITHUB_WORKSPACE"/modem1/image/$i
            fi
            done
            sudo mv "$GITHUB_WORKSPACE"/modem1/image/* "$GITHUB_WORKSPACE"/modem/image/
            sudo umount -v "$GITHUB_WORKSPACE"/modem/
            sudo umount -v "$GITHUB_WORKSPACE"/modem1/
            sudo rm -rf "$GITHUB_WORKSPACE"/images/firmware-update/
       - name: 5.打包
         run: |
            mkdir -p "$GITHUB_WORKSPACE"/images/META-INF/com/google/android/
            touch "$GITHUB_WORKSPACE"/images/META-INF/com/google/android/update-binary
            echo "#!/sbin/sh" > "$GITHUB_WORKSPACE"/images/META-INF/com/google/android/update-binary
            echo "">>"$GITHUB_WORKSPACE"/images/META-INF/com/google/android/update-binary
            echo "OUTFD=/proc/self/fd/\$2" >> "$GITHUB_WORKSPACE"/images/META-INF/com/google/android/update-binary
            echo "ZIPFILE=\"\$3\"" >> "$GITHUB_WORKSPACE"/images/META-INF/com/google/android/update-binary
            echo "">>"$GITHUB_WORKSPACE"/images/META-INF/com/google/android/update-binary
            echo "ui_print() {">>"$GITHUB_WORKSPACE"/images/META-INF/com/google/android/update-binary
            echo "  echo -e \"ui_print \$1\\nui_print\" >>\$OUTFD">>"$GITHUB_WORKSPACE"/images/META-INF/com/google/android/update-binary
            echo "}">>"$GITHUB_WORKSPACE"/images/META-INF/com/google/android/update-binary
            echo "">>"$GITHUB_WORKSPACE"/images/META-INF/com/google/android/update-binary
            echo "package_extract_file() {">>"$GITHUB_WORKSPACE"/images/META-INF/com/google/android/update-binary
            echo "  ui_print \" - 正在刷入 \$(echo \$1 | awk -F \"/\" '{print \$NF}') 至 \$(echo \$2 | awk -F \"/\" '{print \$NF}') 分区\"">>"$GITHUB_WORKSPACE"/images/META-INF/com/google/android/update-binary
            echo "  unzip -p \"\$ZIPFILE\" \$1 >\$2">>"$GITHUB_WORKSPACE"/images/META-INF/com/google/android/update-binary
            echo "}">>"$GITHUB_WORKSPACE"/images/META-INF/com/google/android/update-binary
            echo "">>"$GITHUB_WORKSPACE"/images/META-INF/com/google/android/update-binary
            echo "package_extract_file \"modem.img\" \"/dev/block/bootdevice/by-name/modem\"">>"$GITHUB_WORKSPACE"/images/META-INF/com/google/android/update-binary
            echo "">>"$GITHUB_WORKSPACE"/images/META-INF/com/google/android/update-binary
            echo "ui_print \"刷入完成\"" >>"$GITHUB_WORKSPACE"/images/META-INF/com/google/android/update-binary
            echo "ui_print \"挂载错误信息不用管，直接重启既可\"" >>"$GITHUB_WORKSPACE"/images/META-INF/com/google/android/update-binary
            echo "exit 0" >> "$GITHUB_WORKSPACE"/images/META-INF/com/google/android/update-binary
            sudo 7z a "$GITHUB_WORKSPACE"/zip/miui_LMIPRE_modem.zip "$GITHUB_WORKSPACE"/images/*
            sudo rm -rf "$GITHUB_WORKSPACE"/framework
            mv "$GITHUB_WORKSPACE"/zip/miui_LMIPRE_modem.zip "$GITHUB_WORKSPACE"/zip/miui_LMIPRE_"${{ env.date }}"_modem.zip
            echo "artifact_name=miui_LMIPRE_"${{ env.date }}"_modem" >> $GITHUB_ENV
            cd "$GITHUB_WORKSPACE"
            touch file.log
            echo "miui_LMIPRE_"${{ env.date }}"_modem.zip" > file.log
       - name: 6.上传到Github Release
         uses: ncipollo/release-action@main
         with:
           artifacts: ${{ github.workspace }}/zip/*
           name: "${{ env.date }}_modem"
           tag: "${{ env.date }}_modem"
           bodyFile: "${{ github.workspace }}/file.log"
           allowUpdates: true
           artifactErrorsFailBuild: true
           token: ${{ secrets.GITHUB_TOKEN }}
       - name: 7.删除工作流运行
         uses: Mattraks/delete-workflow-runs@v2
         with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0

