name: build_umi_system
on: 
  workflow_dispatch:
    inputs:
      URL:
        description: '待操作的系统包下载地址'     
        required: true
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        runs-on:
          - ubuntu-22.04
    runs-on: ${{ matrix.runs-on }}
    steps:
       - uses: actions/checkout@master  
       - name: 1.安装依赖
         run: |
            sudo apt install python3 python3-pip aria2 zip p7zip-full tar zipalign
            sudo apt --fix-broken install
            sudo apt update --fix-missing
            pip3 install --upgrade pip
            pip3 install pycryptodome
            pip3 install docopt
            pip3 install requests
            pip3 install beautifulsoup4
            pip3 install --ignore-installed pyyaml

       - name: 4.替换相关文件
         run: |
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/apktool.jar
            Apktool="java -jar "$GITHUB_WORKSPACE"/tools/apktool.jar"
            sudo mkdir -p "$GITHUB_WORKSPACE"/MiuiSystemUI/
            $Apktool d -q -r -f -o "$GITHUB_WORKSPACE"/MiuiSystemUI/ "$GITHUB_WORKSPACE"/images/system_ext/priv-app/MiuiSystemUI/MiuiSystemUI.apk
            sudo sed -i '/^.method protected updateSizeForScreenSizeChange()V/,/^.end method/d' "$GITHUB_WORKSPACE"/MiuiSystemUI/smali*/com/android/keyguard/charge/container/MiuiChargeAnimationView.smali
            mod=$(cat "$GITHUB_WORKSPACE"/files/Smali_Mod.smali)
            echo "$mod" >> "$GITHUB_WORKSPACE"/MiuiSystemUI/smali*/com/android/keyguard/charge/container/MiuiChargeAnimationView.smali
            sudo mkdir -p "$GITHUB_WORKSPACE"/2/MiuiSystemUI/smali/com/android/keyguard/charge/container/MiuiChargeAnimationView.smali
            sudo cp -rf "$GITHUB_WORKSPACE"/"$GITHUB_WORKSPACE"/MiuiSystemUI/smali*/com/android/keyguard/charge/container/MiuiChargeAnimationView.smali "$GITHUB_WORKSPACE"/2/MiuiSystemUI/smali/com/android/keyguard/charge/container/MiuiChargeAnimationView.smali
            sudo cp -rf "$GITHUB_WORKSPACE"/MiuiSystemUI/apktool.yml "$GITHUB_WORKSPACE"/2/MiuiSystemUI/
            $Apktool b -q -f -o "$GITHUB_WORKSPACE"/2/MiuiSystemUI.apk "$GITHUB_WORKSPACE"/2/MiuiSystemUI/
            filepath="$GITHUB_WORKSPACE"/MiuiCamera/one/
            for file in `ls -a $filepath`
            do
              if [ "${file##*.}"x = "dex"x ];then
                old=$(echo $file | tr -d "a-zA-Z" | tr -d ".")
                if [ -Z $old ];then
                   old=1
                fi
                new=$(echo $old|awk '{for(i=1;i<=NF;i++){$i+=1}}1')
                sudo cp -rf "$GITHUB_WORKSPACE"/MiuiCamera/one/$file "$GITHUB_WORKSPACE"/MiuiCamera/three/classes$new.dex
              fi
            done
            
            cd "$GITHUB_WORKSPACE"/MiuiSystemUI/build/apk
            sudo 7z a "$GITHUB_WORKSPACE"/images/system_ext/priv-app/MiuiSystemUI/MiuiSystemUI.apk ./*.dex -mx0
            cd "$GITHUB_WORKSPACE"/files/systemui
            sudo 7z a "$GITHUB_WORKSPACE"/images/system_ext/priv-app/MiuiSystemUI/MiuiSystemUI.apk ./* -mx0
            cd "$GITHUB_WORKSPACE"
            sudo rm -rf "$GITHUB_WORKSPACE"/images/system_ext/priv-app/MiuiSystemUI/MiuiSystemUI/oat
            cd "$GITHUB_WORKSPACE"
            sudo mv "$GITHUB_WORKSPACE"/images/system_ext/priv-app/MiuiSystemUI/MiuiSystemUI.apk "$GITHUB_WORKSPACE"/MiuiSystemUI/MiuiSystemUI.apk
            sudo zipalign -v 4 "$GITHUB_WORKSPACE"/MiuiSystemUI/MiuiSystemUI.apk "$GITHUB_WORKSPACE"/images/system_ext/priv-app/MiuiSystemUI/MiuiSystemUI.apk >/dev/null

       - name: 5.打包
         run: |
            7z a "$GITHUB_WORKSPACE"/zip/systemui.zip "$GITHUB_WORKSPACE"/images/system_ext/priv-app/MiuiSystemUI/
       
       - name: Upload firmware directory
         uses: actions/upload-artifact@main
         with:
            name: zip
            path: zip/systemui.zip
