name: test
on: 
  workflow_dispatch:
    inputs:
      URL:
        description: '待操作的系统包下载地址'     
        required: true
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
       - uses: actions/checkout@master  
       - name: 1.安装依赖
         run: |
            sudo apt install python3 python3-pip aria2 zip p7zip-full
            sudo apt --fix-broken install
            sudo apt update --fix-missing
            pip3 install --upgrade pip
            pip3 install aliyundrive-webdav
       - name: 6.上传到阿里云盘
         run: |
            curl https://rclone.org/install.sh | sudo bash
            mkdir -p ~/.config/rclone/
            unzip -P ${{ secrets.PASSWORD }} "$GITHUB_WORKSPACE"/tools/rclone.zip -d ~/.config/rclone/
            nohup aliyundrive-webdav --refresh-token ${{ secrets.REFRESHTOKEN }} --host 127.0.0.1 --port 6396 --auth-user 3380572517 --auth-password ${{ secrets.PASSWORD }} >/dev/null 2>& 1 &
            rclone mkdir aliyun:/LMI_Package
            rclone sync -P ./tools/rclone.zip aliyun:/LMI_Package
       - name: 7.上传到123盘
         run: |
            curl -fsSL "https://nn.ci/alist.sh" | sudo bash -s install
            sudo systemctl stop alist
            sudo mv -f /home/runner/.config/rclone/data.db /opt/alist/data
            sudo systemctl start alist
            rclone mkdir 123pan:/LMI_Packages
            rclone sync -P ./tools/rclone.zip 123pan:/LMI_Packages
       - name: 8.删除工作流运行
         uses: Mattraks/delete-workflow-runs@v2
         with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
